##########################################################
##########            PRODUCT_SERVICE           ##########
##########     Application file properties      ##########
##########     security/qr/datasource/custom    ##########
##########################################################

##################### SERVER PROP #################################
server:
  port: 8084
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

##################### SPRING GLOBAL #################################
eureka:
  client:
    fetchRegistry: true

spring:
  application:
    name: product-service

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  ##################### DATA SOURCE #################################
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 100
    initialization-mode: always
    ##################### MY SQL DATABASE #################################
    url: jdbc:mysql://localhost:3306/flower_shop_application?serverTimezone=Europe/Moscow
    password: 1111
    username: root
  ##################### JPA USED SPRING DATA #################################
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      format-sql: true
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        event:
          merge:
            entity_copy_observer: allow
      use_sql_comments: true
    show-sql: true
  ##################### SPRING MAIL PROPERTIES #################################
  mail:
    host: smtp.mail.ru
    password: 1999WarehouseLogistic
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true
          timeout: 5000
          writetimeout: 5000
    username: warehouse_logistic_worker@inbox.ru
  messages:
    basename: messages
    encoding: UTF-8





