version: '3.8'

services:

  # MYSQL DB
  flower_shop_db_mysql:
    image: mysql
    container_name: flower_shop_db_mysql
    volumes:
      - d:/DOCKER/data/mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=1111
      - MYSQL_DATABASE=flower_shop_application
    #            - MYSQL_PASSWORD=1111
    restart: always
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']

  adminer:
    image: adminer
    container_name: adminer_db
    restart: always
    ports:
      - '8085:8080'